-- Órdenes de servicio (raw) 2022-2024.
-- Nota: esta tabla está pensada para carga por COPY desde los CSV originales.
--       Se particiona por año para carga incremental y para evitar tablas gigantes.

CREATE UNLOGGED TABLE IF NOT EXISTS raw.orden_servicio (
  orden TEXT,
  ano_eje INT NOT NULL,
  sec_ejec TEXT,
  tipo_bien TEXT,
  nro_orden TEXT,
  fecha_orden TIMESTAMP NULL,
  mes_orden NUMERIC NULL,
  nombre_mes TEXT,
  nro_contrato TEXT,
  id_contrato TEXT,
  id_proceso TEXT,
  id_orden TEXT,
  exp_siaf TEXT,
  estado_siaf TEXT,
  concepto TEXT,
  estado_orden TEXT,
  fuente_financ TEXT,
  sec_func TEXT,
  clasificador TEXT,
  nombre_clasif TEXT,
  id_clasificador TEXT,
  nro_ruc TEXT,
  nombre_prov TEXT,
  grupo_bien TEXT,
  nombre_grupo TEXT,
  clase_bien TEXT,
  nombre_clase TEXT,
  familia_bien TEXT,
  nombre_fam TEXT,
  item_bien TEXT,
  nombre_item TEXT,
  centro_costo TEXT,
  nombre_centro_costo TEXT,
  tipo_tarea TEXT,
  nivel_tarea TEXT,
  codigo_tarea TEXT,
  nombre_tarea TEXT,
  cant_item_ccosto NUMERIC NULL,
  valor_ccosto NUMERIC NULL,
  precio_unit NUMERIC NULL,
  moneda TEXT,
  cant_item_meta NUMERIC NULL,
  valor_meta NUMERIC NULL,
  valor_total_os NUMERIC NULL,
  modif_orden NUMERIC NULL,
  unidad_medida TEXT,
  unidad_medida_item TEXT,
  tipo_proceso TEXT,
  descripcion_tipo_proceso TEXT,
  abreviada_tipo_proceso TEXT,
  modalidad_compra TEXT,
  descripcion_modal_compra TEXT,
  nro_proc_sel TEXT,
  flag_recep_orden TEXT,
  recepcion_orden_proveedor TEXT,
  fecha_recepcion TIMESTAMP NULL,
  flag_ing_almacen TEXT,
  estado_entrada_almacen TEXT,
  estado_devengado TEXT,
  nivel_gobierno TEXT,
  sector TEXT,
  nombre_sector TEXT,
  pliego TEXT,
  nombre_pliego TEXT,
  region TEXT,
  nombre_ejecutora TEXT
) PARTITION BY LIST (ano_eje);

-- Importante (performance): las particiones NO heredan UNLOGGED del parent.
-- Deben crearse explÃ­citamente como UNLOGGED para minimizar WAL.
CREATE UNLOGGED TABLE IF NOT EXISTS raw.orden_servicio_2022 PARTITION OF raw.orden_servicio FOR VALUES IN (2022);
CREATE UNLOGGED TABLE IF NOT EXISTS raw.orden_servicio_2023 PARTITION OF raw.orden_servicio FOR VALUES IN (2023);
CREATE UNLOGGED TABLE IF NOT EXISTS raw.orden_servicio_2024 PARTITION OF raw.orden_servicio FOR VALUES IN (2024);
