-- CMN MEF (raw) - schema estable 2022-2024 y 2025_v2.
-- Se particiona por ano_eje para carga incremental y control de volumen.

CREATE UNLOGGED TABLE IF NOT EXISTS raw.cmn_mef (
  ano_eje BIGINT NOT NULL,
  sec_ejec TEXT,
  fase_programacion TEXT,
  sec_func BIGINT,
  sec_func_prop BIGINT,
  centro_costo TEXT,
  centro_costo_nombre TEXT,
  tipo_uso TEXT,
  clasificador TEXT,
  nombre_clasificador TEXT,
  fuente_financ BIGINT,
  tipo_bien TEXT,
  grupo BIGINT,
  grupo_nombre TEXT,
  clase BIGINT,
  clase_nombre TEXT,
  familia BIGINT,
  familia_nombre TEXT,
  item BIGINT,
  item_nombre TEXT,
  unidad_medida TEXT,
  precio_unit DOUBLE PRECISION,
  cant_01 DOUBLE PRECISION,
  cant_02 DOUBLE PRECISION,
  cant_03 DOUBLE PRECISION,
  cant_04 DOUBLE PRECISION,
  cant_05 DOUBLE PRECISION,
  cant_06 DOUBLE PRECISION,
  cant_07 DOUBLE PRECISION,
  cant_08 DOUBLE PRECISION,
  cant_09 DOUBLE PRECISION,
  cant_10 DOUBLE PRECISION,
  cant_11 DOUBLE PRECISION,
  cant_12 DOUBLE PRECISION,
  cant_total DOUBLE PRECISION,
  mnto_01 DOUBLE PRECISION,
  mnto_02 DOUBLE PRECISION,
  mnto_03 DOUBLE PRECISION,
  mnto_04 DOUBLE PRECISION,
  mnto_05 DOUBLE PRECISION,
  mnto_06 DOUBLE PRECISION,
  mnto_07 DOUBLE PRECISION,
  mnto_08 DOUBLE PRECISION,
  mnto_09 DOUBLE PRECISION,
  mnto_10 DOUBLE PRECISION,
  mnto_11 DOUBLE PRECISION,
  mnto_12 DOUBLE PRECISION,
  mnto_total DOUBLE PRECISION,
  prevision_anno_01 DOUBLE PRECISION,
  opago_anno_01 DOUBLE PRECISION,
  mnto_anno_02 DOUBLE PRECISION,
  prevision_anno_02 DOUBLE PRECISION,
  opago_anno_02 DOUBLE PRECISION,
  mnto_anno_03 DOUBLE PRECISION,
  prevision_anno_03 DOUBLE PRECISION,
  opago_anno_03 DOUBLE PRECISION,
  mnto_anno_04 DOUBLE PRECISION,
  prevision_anno_04 DOUBLE PRECISION,
  opago_anno_04 DOUBLE PRECISION,
  nivel_gobierno TEXT,
  sector TEXT,
  nombre_sector TEXT,
  pliego TEXT,
  nombre_pliego TEXT,
  region TEXT,
  ejecutora_dsc TEXT,
  funcion BIGINT,
  descrip_funcion TEXT,
  programa BIGINT,
  descrip_programa TEXT,
  sub_programa BIGINT,
  descrip_sub_programa TEXT,
  meta TEXT,
  act_proy TEXT,
  act_proy_nombre TEXT,
  componente TEXT,
  descrip_componente TEXT,
  finalidad BIGINT,
  descrip_finalidad TEXT,
  programa_ppto BIGINT,
  descrip_programa_ppto TEXT,
  fecha_reg DATE
) PARTITION BY LIST (ano_eje);

-- Importante (performance): las particiones NO heredan UNLOGGED del parent.
-- Deben crearse explÃ­citamente como UNLOGGED para minimizar WAL.
CREATE UNLOGGED TABLE IF NOT EXISTS raw.cmn_mef_2022 PARTITION OF raw.cmn_mef FOR VALUES IN (2022);
CREATE UNLOGGED TABLE IF NOT EXISTS raw.cmn_mef_2023 PARTITION OF raw.cmn_mef FOR VALUES IN (2023);
CREATE UNLOGGED TABLE IF NOT EXISTS raw.cmn_mef_2024 PARTITION OF raw.cmn_mef FOR VALUES IN (2024);
CREATE UNLOGGED TABLE IF NOT EXISTS raw.cmn_mef_2025 PARTITION OF raw.cmn_mef FOR VALUES IN (2025);
