-- CMN MEF 2025 (raw) - fuente complementaria v1 (schema amplio ~206 columnas).
-- Se mantiene separada de raw.cmn_mef (v2) por diferencias de esquema.

CREATE UNLOGGED TABLE IF NOT EXISTS raw.cmn_mef_2025_v1 (
  sec_ejec TEXT,
  anno BIGINT,
  sede_id BIGINT,
  descrip_sede TEXT,
  direccion TEXT,
  pais BIGINT,
  ubigeo BIGINT,
  nombre_distrito TEXT,
  nombre_pais TEXT,
  centro_costo TEXT,
  descrip_centro_costo TEXT,
  estado_centro_costo BIGINT,
  act_ope_id BIGINT,
  descrip_actividad_operativa TEXT,
  tipo_act_proy BIGINT,
  descrip_tipo_act_proy TEXT,
  act_ope_nivel TEXT,
  descrip_act_ope_nivel TEXT,
  codigo_poi TEXT,
  tipo_uso_act_ope TEXT,
  descrip_tipo_uso_act_ope TEXT,
  estado_act_ope BIGINT,
  fuente_financ BIGINT,
  clasificador TEXT,
  descrip_clasificador_gasto TEXT,
  id_clasificador TEXT,
  tipo_clasificador TEXT,
  flag_abast BIGINT,
  estado_clasif TEXT,
  sec_func BIGINT,
  funcion BIGINT,
  division_funcional BIGINT,
  grupo_funcional BIGINT,
  programa_institucional BIGINT,
  prod_proy BIGINT,
  act_ai_obr BIGINT,
  finalidad BIGINT,
  meta TEXT,
  descrip_meta TEXT,
  ubigeo_meta BIGINT,
  nombre_distrito_meta TEXT,
  catalogo_num BIGINT,
  item_id BIGINT,
  tipo_bien TEXT,
  grupo_bien BIGINT,
  nombre_grupo TEXT,
  clase_bien BIGINT,
  nombre_clase TEXT,
  familia_bien BIGINT,
  nombre_fam TEXT,
  item_bien BIGINT,
  nombre_item TEXT,
  unidad_medida BIGINT,
  nombre_unidad_medida TEXT,
  estado_item TEXT,
  estado_grupo TEXT,
  estado_clase TEXT,
  estado_familia TEXT,
  fase BIGINT,
  cuadro_id BIGINT,
  estado_cn BIGINT,
  cuadro_det_id BIGINT,
  precio_unit DOUBLE PRECISION,
  tipo_uso TEXT,
  descrip_tipo_uso TEXT,
  a2025_cant1 DOUBLE PRECISION,
  a2025_cant2 DOUBLE PRECISION,
  a2025_cant3 DOUBLE PRECISION,
  a2025_cant4 DOUBLE PRECISION,
  a2025_cant5 DOUBLE PRECISION,
  a2025_cant6 DOUBLE PRECISION,
  a2025_cant7 DOUBLE PRECISION,
  a2025_cant8 DOUBLE PRECISION,
  a2025_cant9 DOUBLE PRECISION,
  a2025_cant10 DOUBLE PRECISION,
  a2025_cant11 DOUBLE PRECISION,
  a2025_cant12 DOUBLE PRECISION,
  a2025_canttotal DOUBLE PRECISION,
  a2025_monto1 DOUBLE PRECISION,
  a2025_monto2 DOUBLE PRECISION,
  a2025_monto3 DOUBLE PRECISION,
  a2025_monto4 DOUBLE PRECISION,
  a2025_monto5 DOUBLE PRECISION,
  a2025_monto6 DOUBLE PRECISION,
  a2025_monto7 DOUBLE PRECISION,
  a2025_monto8 DOUBLE PRECISION,
  a2025_monto9 DOUBLE PRECISION,
  a2025_monto10 DOUBLE PRECISION,
  a2025_monto11 DOUBLE PRECISION,
  a2025_monto12 DOUBLE PRECISION,
  a2025_montototal DOUBLE PRECISION,
  a2025_cantoblifina DOUBLE PRECISION,
  a2025_mtooblifina DOUBLE PRECISION,
  a2025_cantprevpres DOUBLE PRECISION,
  a2025_mtoprevpres DOUBLE PRECISION,
  a2026_cant1 DOUBLE PRECISION,
  a2026_cant2 DOUBLE PRECISION,
  a2026_cant3 DOUBLE PRECISION,
  a2026_cant4 DOUBLE PRECISION,
  a2026_cant5 DOUBLE PRECISION,
  a2026_cant6 DOUBLE PRECISION,
  a2026_cant7 DOUBLE PRECISION,
  a2026_cant8 DOUBLE PRECISION,
  a2026_cant9 DOUBLE PRECISION,
  a2026_cant10 DOUBLE PRECISION,
  a2026_cant11 DOUBLE PRECISION,
  a2026_cant12 DOUBLE PRECISION,
  a2026_canttotal DOUBLE PRECISION,
  a2026_monto1 DOUBLE PRECISION,
  a2026_monto2 DOUBLE PRECISION,
  a2026_monto3 DOUBLE PRECISION,
  a2026_monto4 DOUBLE PRECISION,
  a2026_monto5 DOUBLE PRECISION,
  a2026_monto6 DOUBLE PRECISION,
  a2026_monto7 DOUBLE PRECISION,
  a2026_monto8 DOUBLE PRECISION,
  a2026_monto9 DOUBLE PRECISION,
  a2026_monto10 DOUBLE PRECISION,
  a2026_monto11 DOUBLE PRECISION,
  a2026_monto12 DOUBLE PRECISION,
  a2026_montototal DOUBLE PRECISION,
  a2026_cantoblifina DOUBLE PRECISION,
  a2026_mtooblifina DOUBLE PRECISION,
  a2026_cantprevpres DOUBLE PRECISION,
  a2026_mtoprevpres DOUBLE PRECISION,
  a2027_cant1 DOUBLE PRECISION,
  a2027_cant2 DOUBLE PRECISION,
  a2027_cant3 DOUBLE PRECISION,
  a2027_cant4 DOUBLE PRECISION,
  a2027_cant5 DOUBLE PRECISION,
  a2027_cant6 DOUBLE PRECISION,
  a2027_cant7 DOUBLE PRECISION,
  a2027_cant8 DOUBLE PRECISION,
  a2027_cant9 DOUBLE PRECISION,
  a2027_cant10 DOUBLE PRECISION,
  a2027_cant11 DOUBLE PRECISION,
  a2027_cant12 DOUBLE PRECISION,
  a2027_canttotal DOUBLE PRECISION,
  a2027_monto1 DOUBLE PRECISION,
  a2027_monto2 DOUBLE PRECISION,
  a2027_monto3 DOUBLE PRECISION,
  a2027_monto4 DOUBLE PRECISION,
  a2027_monto5 DOUBLE PRECISION,
  a2027_monto6 DOUBLE PRECISION,
  a2027_monto7 DOUBLE PRECISION,
  a2027_monto8 DOUBLE PRECISION,
  a2027_monto9 DOUBLE PRECISION,
  a2027_monto10 DOUBLE PRECISION,
  a2027_monto11 DOUBLE PRECISION,
  a2027_monto12 DOUBLE PRECISION,
  a2027_montototal DOUBLE PRECISION,
  a2027_cantoblifina DOUBLE PRECISION,
  a2027_mtooblifina DOUBLE PRECISION,
  a2027_cantprevpres DOUBLE PRECISION,
  a2027_mtoprevpres DOUBLE PRECISION,
  a2028_cant1 DOUBLE PRECISION,
  a2028_cant2 DOUBLE PRECISION,
  a2028_cant3 DOUBLE PRECISION,
  a2028_cant4 DOUBLE PRECISION,
  a2028_cant5 DOUBLE PRECISION,
  a2028_cant6 DOUBLE PRECISION,
  a2028_cant7 DOUBLE PRECISION,
  a2028_cant8 DOUBLE PRECISION,
  a2028_cant9 DOUBLE PRECISION,
  a2028_cant10 DOUBLE PRECISION,
  a2028_cant11 DOUBLE PRECISION,
  a2028_cant12 DOUBLE PRECISION,
  a2028_canttotal DOUBLE PRECISION,
  a2028_monto1 DOUBLE PRECISION,
  a2028_monto2 DOUBLE PRECISION,
  a2028_monto3 DOUBLE PRECISION,
  a2028_monto4 DOUBLE PRECISION,
  a2028_monto5 DOUBLE PRECISION,
  a2028_monto6 DOUBLE PRECISION,
  a2028_monto7 DOUBLE PRECISION,
  a2028_monto8 DOUBLE PRECISION,
  a2028_monto9 DOUBLE PRECISION,
  a2028_monto10 DOUBLE PRECISION,
  a2028_monto11 DOUBLE PRECISION,
  a2028_monto12 DOUBLE PRECISION,
  a2028_montototal DOUBLE PRECISION,
  a2028_cantoblifina DOUBLE PRECISION,
  a2028_mtooblifina DOUBLE PRECISION,
  a2028_cantprevpres DOUBLE PRECISION,
  a2028_mtoprevpres DOUBLE PRECISION,
  obli_fina_precio_unit DOUBLE PRECISION,
  obli_fina_docum_tipo BIGINT,
  obli_fina_docum_nro TEXT,
  prev_pres_docum_tipo BIGINT,
  prev_pres_docum_nro TEXT,
  fecha_carga TEXT,
  estado_cn_desc TEXT,
  fase_programacion TEXT,
  nivel_gobierno TEXT,
  sector BIGINT,
  nombre_sector TEXT,
  pliego BIGINT,
  nombre_pliego TEXT,
  region TEXT,
  ejecutora_nombre TEXT,
  ruc_entidad BIGINT,
  ano_eje BIGINT,
  sec_ejec_raw TEXT,
  cc_raw TEXT,
  sec_ejec2 TEXT,
  centro_costo2 TEXT
);
