-- CMN MINEDU (raw) - union de schema 2022-2025 (2025 incluye 4 columnas extra).
-- Se particiona por ano_eje para carga incremental y control de volumen.

CREATE UNLOGGED TABLE IF NOT EXISTS raw.cmn_minedu (
  sector TEXT,
  nombre_sector TEXT,
  pliego TEXT,
  nombre_pliego TEXT,
  ano_eje BIGINT NOT NULL,
  sec_ejec TEXT,
  ejecutora_nombre TEXT,
  fase_programacion TEXT,
  centro_costo TEXT,
  centro_costo_nombre TEXT,
  punto_atencion_nombre TEXT,
  cod_categoria TEXT,
  categoria_nombre TEXT,
  cod_modular TEXT,
  ubigeo TEXT,
  pp BIGINT,
  nombre_pp_nombre TEXT,
  nivel_tarea TEXT,
  producto BIGINT,
  meta_propuesta TEXT,
  cod_funcion TEXT,
  nombre_funcion TEXT,
  grupo_funcional TEXT,
  producto_nombre TEXT,
  cod_actividad TEXT,
  actividad_nombre TEXT,
  sub_producto BIGINT,
  sub_producto_nombre TEXT,
  sub_producto_trazador TEXT,
  cantidad DOUBLE PRECISION,
  tipo_uso TEXT,
  clasificador TEXT,
  fuente_financ BIGINT,
  nombre_fuente_financ TEXT,
  tipo_bien TEXT,
  grupo BIGINT,
  grupo_nombre TEXT,
  clase BIGINT,
  clase_nombre TEXT,
  familia BIGINT,
  familia_nombre TEXT,
  item TEXT,
  item_nombre TEXT,
  unidad_medida TEXT,
  precio_unit DOUBLE PRECISION,
  cant_01 DOUBLE PRECISION,
  cant_02 DOUBLE PRECISION,
  cant_03 DOUBLE PRECISION,
  cant_04 DOUBLE PRECISION,
  cant_05 DOUBLE PRECISION,
  cant_06 DOUBLE PRECISION,
  cant_07 DOUBLE PRECISION,
  cant_08 DOUBLE PRECISION,
  cant_09 DOUBLE PRECISION,
  cant_10 DOUBLE PRECISION,
  cant_11 DOUBLE PRECISION,
  cant_12 DOUBLE PRECISION,
  cant_total DOUBLE PRECISION,
  mnto_01 DOUBLE PRECISION,
  mnto_02 DOUBLE PRECISION,
  mnto_03 DOUBLE PRECISION,
  mnto_04 DOUBLE PRECISION,
  mnto_05 DOUBLE PRECISION,
  mnto_06 DOUBLE PRECISION,
  mnto_07 DOUBLE PRECISION,
  mnto_08 DOUBLE PRECISION,
  mnto_09 DOUBLE PRECISION,
  mnto_10 DOUBLE PRECISION,
  mnto_11 DOUBLE PRECISION,
  mnto_12 DOUBLE PRECISION,
  mnto_total DOUBLE PRECISION,
  prevision_anno_01 DOUBLE PRECISION,
  opago_anno_01 DOUBLE PRECISION,
  mnto_anno_02 DOUBLE PRECISION,
  prevision_anno_02 DOUBLE PRECISION,
  opago_anno_02 DOUBLE PRECISION,
  mnto_anno_03 DOUBLE PRECISION,
  prevision_anno_03 DOUBLE PRECISION,
  opago_anno_03 DOUBLE PRECISION,
  mnto_anno_04 DOUBLE PRECISION,
  prevision_anno_04 DOUBLE PRECISION,
  opago_anno_04 DOUBLE PRECISION,
  region TEXT,
  fecha_corte DATE,
  sec_ejec_raw TEXT,
  cc_raw TEXT,
  sec_ejec2 TEXT,
  centro_costo2 TEXT
) PARTITION BY LIST (ano_eje);

-- Importante (performance): las particiones NO heredan UNLOGGED del parent.
-- Deben crearse explícitamente como UNLOGGED para minimizar WAL.
CREATE UNLOGGED TABLE IF NOT EXISTS raw.cmn_minedu_2022 PARTITION OF raw.cmn_minedu FOR VALUES IN (2022);
CREATE UNLOGGED TABLE IF NOT EXISTS raw.cmn_minedu_2023 PARTITION OF raw.cmn_minedu FOR VALUES IN (2023);
CREATE UNLOGGED TABLE IF NOT EXISTS raw.cmn_minedu_2024 PARTITION OF raw.cmn_minedu FOR VALUES IN (2024);
CREATE UNLOGGED TABLE IF NOT EXISTS raw.cmn_minedu_2025 PARTITION OF raw.cmn_minedu FOR VALUES IN (2025);
